services:
  database:
    image: postgres:16-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin123
      - POSTGRES_DB=aprendiendo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: